### ISSUE TITLE
can’t find .glyphsfilter file

### ISSUE THREAD

**Issue by synthview** [simoncozens/Callipers#3]
Hello,
where can I download the plugin?

Thanks

**Comment by simoncozens** [comment]
The latest version is here: https://github.com/simoncozens/Callipers/releases/download/beta-4/Callipers-beta-4.zip

For future releases, look for `Callipers-... .zip` on this page: https://github.com/simoncozens/Callipers/releases

**Comment by synthview** [comment]
Thanks, found meanwhile.
It could be useful to put a link on this page I guess
https://github.com/simoncozens/Callipers

BTW, I feel that colours do not convey information clearly enough. I’d use only 1 axis, for instance green to red = even to uneven. Using another colour as blue seems confusing.
Also a numeric ratio value could be useful to compare among glyphs, or to get a more precise result. Changing strokes thickness and step doesn’t seem adding any information to me. Please look at the speedpunk plugin from Yanone. His graphical representation of curves equations is very effective.  
You can find another great example in the FontLab 6 beta: a ruler that automatically sets as perpendicular to 2 paths and dynamically showing the distance value while moving across the glyph.
Best,

**Comment by simoncozens** [comment]
Thank you for your ideas!
